---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-clusterplus-io-v1-plus
  failurePolicy: Fail
  name: mplus.kb.io
  rules:
  - apiGroups:
    - apps.clusterplus.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pluses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-clusterplus-io-v1-plus
  failurePolicy: Fail
  name: vplus.kb.io
  rules:
  - apiGroups:
    - apps.clusterplus.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pluses
  sideEffects: None
