apiVersion: apps.clusterplus.io/v1
kind: Plus
metadata:
  name: gateway
spec:
  gateway:
    cors:
      allowOrigins:
        - api-fat.tanjingmama.cn
    hosts:
      - api-fat.tanjingmama.cn
    route: # 指定路由进入环境
      blue:
        headersMatch:
        - MerchantId: "1"
          MerchantType: "type1"
      green:
        headersMatch:
        - MerchantId: "2"
          MerchantType: "type2"
    weights: # 默认路由权重
      blue: 50
      green: 50
  policy:
    timeout: 10s
    maxRequests: 10000
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx
    outlierDetection:
      consecutiveErrors: 5000
      ejectionPercent: 50
      ejectionTime: 30s
      interval: 10s
  apps:
    - version: blue
      env:
        - name: VERSION
          value: blue_version
      image: xyctruth/plus-test:v0.0.8
      minReplicas: 1
      maxReplicas: 10
      port: 8080
      protocol: http
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 250Mi
    - version: green
      env:
        - name: VERSION
          value: green_version
      image: xyctruth/plus-test:v0.0.8
      minReplicas: 1
      maxReplicas: 10
      port: 8080
      protocol: http
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 250Mi

