apiVersion: apps.clusterplus.io/v1
kind: Plus
metadata:
  name: svc-a
spec:
  policy:
    timeout: 10s
    maxRequests: 1000
    retries:
      attempts: 5000
      perTryTimeout: 2s
      retryOn: 5xx
    outlierDetection:
      consecutiveErrors: 5
      ejectionPercent: 100
      ejectionTime: 30s
      interval: 100s
  apps:
    - version: blue
      env:
        - name: VERSION
          value: blue_version
      image: xyctruth/plus-test:v0.0.10
      minReplicas: -1
      maxReplicas: -1
      port: 8080
      protocol: http
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
    - version: green
      env:
        - name: VERSION
          value: green_version
      image: xyctruth/plus-test:v0.0.10
      minReplicas: 1
      maxReplicas: 10
      port: 8080
      protocol: http
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
