apiVersion: apps.clusterplus.io/v1
kind: Plus
metadata:
  name: gateway
spec:
  gateway:
    hosts:
      - api-fat.tanjingmama.cn
    weights: # 默认路由权重
      blue: 50
      green: 50
    #pathPrefix: ""
    route: # 指定路由进入环境
      blue:
        headersMatch:
        - MerchantId: "1"
      green:
        headersMatch:
        - MerchantId: "2"
  policy:
    timeout: 10s
    maxRequests: 10000
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx
    outlierDetection:
      consecutiveErrors: 5000
      ejectionPercent: 50
      ejectionTime: 30s
      interval: 10s
  apps:
    - version: blue
      env:
        - name: VERSION
          value: blue_version
        - name: ENV
          value: fat
        - name: ENV
          value: fat
      image: xyctruth/plus-test:v0.0.10
      imagePullSecrets: imageSecretName
      minReplicas: 1
      maxReplicas: 10
      port: 8080
      protocol: http
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
      readinessProbe:
        httpPath: /
        initialDelaySeconds: 10
      livenessProbe:
        httpPath: /
      hostAliases:
        - ip: 1.1.1.1
          hostnames:
            - "123"
    - version: green
      env:
        - name: VERSION
          value: green_version
      image: xyctruth/plus-test:v0.0.10
      minReplicas: 1
      maxReplicas: 10
      port: 8080
      protocol: http
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi

