apiVersion: apps.clusterplus.io/v1
kind: Plus
metadata:
  name: svc-a
spec:
  policy:
    timeout: 10s
    maxRequests: 1000
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx
    outlierDetection:
      consecutiveErrors: 5000
      ejectionPercent: 100
      ejectionTime: 30s
      interval: 10s
  apps:
    - version: blue
      env:
        - name: VERSION
          value: blue_version
      image: xyctruth/plus-test:v0.0.8
      minReplicas: 1
      maxReplicas: 10
      port: 8080
      protocol: http
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 250Mi
    - version: green
      env:
        - name: VERSION
          value: green_version
      image: xyctruth/plus-test:v0.0.8
      minReplicas: 1
      maxReplicas: 10
      port: 8080
      protocol: http
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 250Mi
