apiVersion: apps.clusterplus.io/v1
kind: Plus
metadata:
  name: gateway
spec:
  gateway:
    hosts:
      - api-fat.tanjingmama.cn
    weights: # 默认路由权重
      blue: 100
      green: 0
    pathPrefix: "gateway-demo"
    route: # 指定路由进入环境
      blue:
        headersMatch:
        - MerchantId: "1123"
      green:
        headersMatch:
        - MerchantId: "2"
  policy:
    timeout: 10s
    maxRequests: 10000
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx
    outlierDetection:
      consecutiveErrors: 5000
      ejectionPercent: 50
      ejectionTime: 30s
      interval: 10s
  apps:
    - version: blue
      rollingUpdateType: "Recreate"  # 默认滚动更新RollingUpdate, Recreate 在创建新的pod之前杀死所有现有的pod
      templateLabels:
        aaa: bbb
      templateAnnotations:
        koordinator.sh/cpuBurst: '{"policy": "auto"}'
        koordinator.sh/cpuBurst1: '{"policy": "auto"}'
        koordinator.sh/cpuBurst2: '{"policy": "auto"}'
      env:
        - name: VERSION
          value: blue_version
        - name: ENV
          value: fat
        - name: ENV
          value: fat
      image: xyctruth/plus-test:v0.0.11
      imagePullSecrets: imageSecretName
      minReplicas: 1
      maxReplicas: 10
      port: 8080
      protocol: http
#      nodeSelector:
#        haha: haha1
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
#      readinessProbe:
#        #httpPath: /
#        execCommand:
#          - "/bin/grpc_health_probe"
#          - "-addr=:8080"
#      livenessProbe:
#        #httpPath: /
#        execCommand:
#          - "/bin/grpc_health_probe"
#          - "-addr=:8080"
      hostAliases:
        - ip: 1.1.1.1
          hostnames:
            - "123"
      tolerations:
        - key: "key1"
          value: "v1"
          effect: "NoSchedule"
    - version: green
      env:
        - name: VERSION
          value: green_version
      image: xyctruth/plus-test:v0.0.11
      minReplicas: 1
      maxReplicas: 1
      port: 8080
      protocol: http
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
