name: Deployment

concurrency: development

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: true
        default: ''

jobs:

  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Get the version
        id: get_version
        run: |
          echo $GITHUB_EVENT_NAME

          if [[ $GITHUB_EVENT_NAME == "workflow_dispatch" ]]; then
            VERSION=${{ github.event.inputs.version }}
          fi

          if [[ $GITHUB_EVENT_NAME == "release" ]]; then
            VERSION=${{ github.event.release.tag_name }}
          fi
          echo ::set-output name=VERSION::${VERSION}
      - uses: actions/checkout@v3
      - uses: infraway/generate-kube-config@v1.2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG_DEV }}
      - name: Deploy
        id: deploy
        run: |
          make deploy IMG=docker.io/xyctruth/clusterplus:${{ steps.get_version.outputs.VERSION }}
