name: Release

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
            VERSION=latest
          fi
          echo ::set-output name=VERSION::${VERSION}

      - name: Login docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: xyctruth
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Push Docker
        id: docker_build_push
        run: |
          make docker-build docker-push  IMG=docker.io/xyctruth/clusterplus:${{ steps.get_version.outputs.VERSION }}

