name: Release

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
            VERSION=latest
          fi
          echo ::set-output name=VERSION::${VERSION}

      - name: Get git revision
        id: vars
        shell: bash
        run: |
          echo "::set-output name=git_revision::$(git rev-parse --short HEAD)"

      - name: Login docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: xyctruth
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get git revision
        id: vars
        shell: bash
        run: |
          make docker-build docker-push  IMG=docker.io/xyctruth/clusterplus:${{ steps.get_version.outputs.VERSION }}
